input {

  file {
    path => "/data/in/waf-*.log"
    mode => "read"
    exit_after_read => true
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json { }
    type => "isc-cloudfront-waf"
  }

  file {
    path => "/data/in/access-*.log"
    mode => "read"
    exit_after_read => true
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => plain { }
    type => "isc-cloudfront-standard-access-logs"
  }

}
